config/routes.rb
Rails.application.routes.draw do
  resources :types do
    resources :businesses
  end
  root 'types#index'

end

app/models/business.rb
class Business < ActiveRecord::Base
  belongs_to :type
end

app/models/type.rb
class Type < ActiveRecord::Base
  has_many :businesses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/business_controller.rb
class BusinessController < ApplicationController
  def index
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  def index
    @types = Type.all
    render :index
  end

  def show
    @type = Type.find(params[:id])
    render :show
  end

  def new
    @type = Type.new
    render :new
  end

  def create
    @type = Type.new(type_params)
    if @type.save
      redirect_to types_path
    else
      render :new
    end
  end

  def delete
    @type = Type.find(params[:id])
  end

  def destroy
    @type = Type.find(params[:id])
    @type.destroy
    redirect_to types_path
  end

  def edit
    @type = Type.find(params[:id])
    render :edit
  end

  def update
    @type = Type.find(params[:id])
    @type.update(type_params)
    if @type.save
      redirect_to types_path
    else
      render :edit
    end     
  end

  private
    def type_params
      params.require(:type).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wikipages</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/types/edit.html.erb
<h1>Edit Business Category/Type</h1>

<%= form_for @type do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/types/index.html.erb
<h1>Wikipages</h1>

<h3>Business Categories:</h3>
<% if @types.length != 0 %>
  <ul>
  <% @types.each do |type| %>
    <li>
      <%= link_to type.name, type_path(type) %> |
      <%= link_to 'Delete', type_path(type), :method => :destroy %> |
      <%= link_to 'Edit', edit_type_path(type) %>
    </li>
  <% end %>
  </ul>
<% end %>

<%= link_to 'Add a New Business Type', new_type_path %>

app/views/types/new.html.erb
<h1>New Business Category/Type</h1>

<%= form_for @type do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/types/show.html.erb
<h3><%= @type.name %></h3>

<% if @type.businesses.any? %>
  <ul>
    <% @type.businesses.each do |business| %>
      <li><%= link_to business.name, business_path(business) %></li>
    <% end %>
  </ul>
<% end %>

<%= link_to 'Home', types_path %>